# Generated by Django 4.1.3 on 2022-11-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeathcareApp', '0003_discover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discover',
        ),
    ]
