# Generated by Django 4.1.3 on 2022-11-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeathcareApp', '0004_delete_discover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('cname', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='HeathcareApp.country')),
                ('first_enc_date', models.DateField()),
                ('disease_code', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='HeathcareApp.disease')),
            ],
        ),
    ]
