# Generated by Django 4.1.3 on 2022-11-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeathcareApp', '0008_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicServant',
        ),
    ]
