# Generated by Django 4.1.3 on 2022-11-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeathcareApp', '0009_delete_publicservant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicServant',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='HeathcareApp.users')),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
