# Generated by Django 4.1.3 on 2022-11-17 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeathcareApp', '0011_specialize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_deaths', models.IntegerField()),
                ('total_patients', models.IntegerField()),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeathcareApp.country')),
                ('disease_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeathcareApp.disease')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeathcareApp.publicservant')),
            ],
        ),
    ]
